
public class OverrideAutoGenerated {
	private String info;
	private int counter;

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@java.lang.Override
	public String toString() {
		return "OverrideAutoGenerated [info=" + info + ", counter=" + counter + "]";
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@java.lang.Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + counter;
		result = prime * result + ((info == null) ? 0 : info.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@java.lang.Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof OverrideAutoGenerated)) {
			return false;
		}
		OverrideAutoGenerated other = (OverrideAutoGenerated) obj;
		if (counter != other.counter) {
			return false;
		}
		if (info == null) {
			if (other.info != null) {
				return false;
			}
		} else if (!info.equals(other.info)) {
			return false;
		}
		return true;
	}

	public OverrideAutoGenerated(String info, int counter) {
		super();
		this.info = info;
		this.counter = counter;
	}

	public OverrideAutoGenerated() {
		super();
		// TODO Auto-generated constructor stub
	}

}
