import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

class OverrideAutoGeneratedTest {

	static OverrideAutoGenerated var1;
	@BeforeAll
	static void setUp() {
		var1 = new OverrideAutoGenerated("test1", 243);
		
	}
	@Test
	void testHashCode() {
//		fail("Not yet implemented"); // TODO
	}

	@Test
	void testToString() {
		String expResult = "OverrideAutoGenerated [info=test1, counter=243]";
		String result = var1.toString();
		assertEquals(expResult, result);
	}

	@Test
	void testEqualsObject() {
	//	fail("Not yet implemented"); // TODO
	}

	@Test
	void testOverrideAutoGeneratedStringInt() {
		//fail("Not yet implemented"); // TODO
	}

}
