
public class OverrideTester {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		OverrideAutoGenerated o1 = new OverrideAutoGenerated( "Test",12);
		System.out.println(o1);
		
		OverrideMy o2 = new OverrideMy( "Test",12);
		System.out.println(o2);

	}

}
